tunnels:
  jeckroth: 0
  dplante: 1
  dummy: 2

operations:

  solo_linux:

    type: one-user-per-vm
    theater: solo_linux
    base_ip: 192.168.123
    users:
      - jeckroth
      - dummy

  team_example:

    type: groups
    theater: web_db_servers
    base_ip: 192.168.124
    groups:
      groupA:
        - jeckroth
        - dplante
      groupB:
        - dummy

